name: dormitory_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2
  get_it: ^7.6.0
  equatable: ^2.0.5
  google_sign_in: ^6.1.4
  formz: ^0.6.0
  flutter_secure_storage: ^8.0.0
  flutter_screenutil: ^5.7.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  easy_localization: ^3.0.2
  flutter_svg: ^2.0.5
  pinput: ^3.0.0
  intl: ^0.18.0
  bloc: ^8.1.2
  animations: ^2.0.7
  google_fonts: ^4.0.4
  flutter_switch: ^0.3.2
  flutter_chat_types: ^3.6.2
  flutter_link_previewer: ^3.2.2
  flutter_parsed_text: ^2.2.1
  mime: ^1.0.4
  open_filex: ^4.3.2
  path_provider: ^2.0.15
  uuid: ^3.0.7
  image_picker: ^1.0.0
  flutter_chat_ui: ^1.6.9
  file_picker: ^5.3.3
  country_calling_code_picker: ^2.0.1
  flutter_native_splash: ^2.3.2
  expandable: ^5.0.1
  showcaseview: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: null

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/messages.json


flutter_native_splash:
  color: "#F1C111"
  image: assets/images/splash_screen.png
  android_12: null
