name: dormitory_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2
  get_it: ^7.6.0
  equatable: ^2.0.5
  google_sign_in: ^6.1.4
  formz: ^0.6.0
  flutter_secure_storage: ^8.0.0
  flutter_screenutil: ^5.7.0
  flutter_form_builder: ^8.0.0
  form_builder_validators: ^8.6.1
  easy_localization: ^3.0.2
  flutter_svg: ^2.0.5
  pinput: ^3.0.0
  intl: ^0.17.0
  bloc: ^8.1.2
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
